language: go

go:
- 1.17

install:
- go get -v -t ./...

before_script:
- go install github.com/mattn/goveralls

script:
- go vet ./...
- go build ./...
- go test ./... -cover=1 -coverprofile=_c.cov
- go test ./... -race
- $GOPATH/bin/goveralls -service=travis-ci -coverprofile=_c.cov
